### ISSUE TITLE
Upload choking internet speed

### ISSUE THREAD

**Issue by silveroxides** [huggingface/hf_transfer#46]
### System Info

hf_transfer==0.1.6, Windows 11, Python version 3.10.9, huggingface_hub==0.23.4

While having the environment variable 'HF_HUB_ENABLE_HF_TRANSFER' set to 1 the upload speeds attempted by hf_transfer completely chokes my connection and pretty much causes Denial Of Service.
My internet connection is rated at 250/250 Mbit/s yet it still seems to attempt to push far beyond that and all other connections on Local Network stops working properly due to it. 
In fact when setting the the variable to 0 I end up uploading faster than with it set to 1 due to it not choking the connection repeatedly

### Reproduction

Unsure if it is reproducible that easily however there might be some ways to mitigate it by pre-checking speed or manually setting some form of upper limit

### Expected behavior

Being able to upload faster with HF_HUB_ENABLE_HF_TRANSFER set to 1 compared to HF_HUB_ENABLE_HF_TRANSFER set to 0 and not having my entire internet connection getting choked

**Comment by Narsil** [comment]
Unfortunately this is working as intended.

`hf_transfer` doesn't aim to be a silver bullet solving everyone's problem (which is why it's not ON by default and has to be opted in).
`hf_transfer` works by saturating the network over multiple connections. It's only useful for bypassing some S3 limitations over single connections and going beyond 500MB/s in certain circumstances. If it saturates your router or any kind of hardware on the line, it's unfortunately normal.

Adding any form of saturation detection would slow down those use cases while attempting to solve the case your doing here.
Not using `hf_transfer` is the solution you should be using.
